### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by davidrivera** [waterlock/waterlock-ldap-auth#2]
Hey man, thanks for making this! If you would like we can move this over to the official Waterlock organization and I can add you to the team.

**Comment by fladi** [comment]
Sure, should I just transfer ownership to the `waterlock` org?

**Comment by davidrivera** [comment]
@fladi yea! I invited you to the waterlock team. So you should be able to migrate the project now!

**Comment by fladi** [comment]
Just tried to transfer the repo but it seems that I would need admin rights on the waterlock org to do this.

**Comment by davidrivera** [comment]
@fladi I just made you an admin, go for it!

**Comment by fladi** [comment]
@davidrivera Transfer was successful. Could you set the permissions for the teams as required and drop my admin privileges again?
